"""initial schema

Revision ID: 29394d2b65e3
Revises: 
Create Date: 2026-05-05 18:56:13.284910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29394d2b65e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comision_materia_codigo'), 'comision', ['materia_codigo'], unique=False)
    op.create_index(op.f('ix_conversacion_usuario_id'), 'conversacion', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_correlatividad_materia_codigo'), 'correlatividad', ['materia_codigo'], unique=False)
    op.create_index(op.f('ix_correlatividad_materia_requerida'), 'correlatividad', ['materia_requerida'], unique=False)
    op.create_index(op.f('ix_horario_comision_id'), 'horario', ['comision_id'], unique=False)
    op.create_index(op.f('ix_horario_consulta_profesor_id'), 'horario_consulta', ['profesor_id'], unique=False)
    op.create_index(op.f('ix_materia_profesor_materia_codigo'), 'materia_profesor', ['materia_codigo'], unique=False)
    op.create_index(op.f('ix_materia_profesor_profesor_id'), 'materia_profesor', ['profesor_id'], unique=False)
    op.create_index(op.f('ix_mensaje_conversacion_id'), 'mensaje', ['conversacion_id'], unique=False)
    op.drop_constraint(op.f('usuario_email_key'), 'usuario', type_='unique')
    op.create_unique_constraint(op.f('uq_usuario_email'), 'usuario', ['email'])
    op.alter_column('usuario_materia', 'condicion',
               existing_type=postgresql.ENUM('aprobado', 'regular', 'cursando', 'libre', 'none', name='condicion_enum'),
               nullable=False,
               existing_server_default=sa.text("'none'::condicion_enum"))
    op.create_index(op.f('ix_usuario_materia_materia_codigo'), 'usuario_materia', ['materia_codigo'], unique=False)
    op.create_index(op.f('ix_usuario_materia_usuario_id'), 'usuario_materia', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_materia_usuario_id'), table_name='usuario_materia')
    op.drop_index(op.f('ix_usuario_materia_materia_codigo'), table_name='usuario_materia')
    op.alter_column('usuario_materia', 'condicion',
               existing_type=postgresql.ENUM('aprobado', 'regular', 'cursando', 'libre', 'none', name='condicion_enum'),
               nullable=True,
               existing_server_default=sa.text("'none'::condicion_enum"))
    op.drop_constraint(op.f('uq_usuario_email'), 'usuario', type_='unique')
    op.create_unique_constraint(op.f('usuario_email_key'), 'usuario', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_mensaje_conversacion_id'), table_name='mensaje')
    op.drop_index(op.f('ix_materia_profesor_profesor_id'), table_name='materia_profesor')
    op.drop_index(op.f('ix_materia_profesor_materia_codigo'), table_name='materia_profesor')
    op.drop_index(op.f('ix_horario_consulta_profesor_id'), table_name='horario_consulta')
    op.drop_index(op.f('ix_horario_comision_id'), table_name='horario')
    op.drop_index(op.f('ix_correlatividad_materia_requerida'), table_name='correlatividad')
    op.drop_index(op.f('ix_correlatividad_materia_codigo'), table_name='correlatividad')
    op.drop_index(op.f('ix_conversacion_usuario_id'), table_name='conversacion')
    op.drop_index(op.f('ix_comision_materia_codigo'), table_name='comision')
    # ### end Alembic commands ###
