"""add unique constraint usuario_materia

Revision ID: 6ff16f5c4cea
Revises: 29394d2b65e3
Create Date: 2026-05-06 22:46:19.433903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff16f5c4cea'
down_revision: Union[str, Sequence[str], None] = '29394d2b65e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_usuario_materia', 'usuario_materia', ['usuario_id', 'materia_codigo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_materia', 'usuario_materia', type_='unique')
    # ### end Alembic commands ###
